default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stock_development
  username: root
  password: admin
  host: localhost

test:
  <<: *default
  database: stock_test

production:
  <<: *default
  database: stock_production
  username: root
  password: <%= ENV['PINME_DATABASE_PASSWORD'] %>