# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b98443991d9a2b766586f9361d9d94fa152f94bbbbb6256204e816c579a7c209c3a03180bfea217476f4222dbbd96ee3f6a9f8ffe4b0c68227749e9698435285

test:
  secret_key_base: e794e3e75d08ca67b20d2d57b92a5d39aa8adc2cb10bef36c0dc82023f2ff1d02afd3b17c9e9aac36f6aa440604ebba533223d07285dad966a31992f467de6b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
